baseURL = 'https://jiten-thakkar.com/'
languageCode = 'en-us'
title = 'Jiten Thakkar'
theme = 'hugo-theme-stack'

# Disqus
[services]
  [services.disqus]
    shortname = 'jitenthakkarcom'

[params]
  mainSections = ['posts']
  featuredImageField = 'image'
  rssFullContent = true
  favicon = '/favicon.ico'
  customSCSS = ['custom/custom.scss']

  [params.footer]
    since = 2012
    customText = ''

  [params.dateFormat]
    published = 'Jan 02, 2006'
    lastUpdated = 'Jan 02, 2006 15:04 MST'

  [params.sidebar]
    emoji = ''
    subtitle = 'Software Engineer at Google working on ML performance. I am also obsessed about history.'

    [params.sidebar.avatar]
      enabled = true
      local = false
      src = '/images/dp_400x400.jpg'

  [params.article]
    math = false
    toc = true
    readingTime = true

    [params.article.license]
      enabled = false
      default = 'Licensed under CC BY-NC-SA 4.0'

  [params.comments]
    enabled = true
    provider = 'disqus'

    [params.comments.disqusjs]
      shortname = 'jitenthakkarcom'
      apiUrl = ''
      apiKey = ''
      admin = ''
      adminLabel = ''

  [[params.widgets.homepage]]
    type = 'search'

  [[params.widgets.homepage]]
    type = 'archives'

  [[params.widgets.homepage]]
    type = 'tag-cloud'

  [[params.widgets.page]]
    type = 'toc'

    [params.widgets.archives]
      limit = 5

    [params.widgets.tagCloud]
      limit = 10

  [params.opengraph]
    [params.opengraph.twitter]
      site = '@jiten_mt'
      card = 'summary_large_image'

  [params.defaultImage]
    [params.defaultImage.opengraph]
      enabled = false
      local = false
      src = ''

  [params.colorScheme]
    toggle = true
    default = 'auto'

  [params.imageProcessing]
    [params.imageProcessing.cover]
      enabled = true
    [params.imageProcessing.content]
      enabled = true

# Menu
[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    [menu.main.params]
      icon = 'user'
      newTab = false
    weight = 1

  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    [menu.main.params]
      icon = 'home'
      newTab = false
    weight = 2

  [[menu.main]]
    identifier = 'archives'
    name = 'Archives'
    url = '/archives/'
    [menu.main.params]
      icon = 'archives'
      newTab = false
    weight = 3

  [[menu.main]]
    identifier = 'gallery'
    name = 'Gallery'
    url = '/gallery/'
    [menu.main.params]
      icon = 'link'
      newTab = false
    weight = 4

  # Social links in sidebar
  [[menu.social]]
    identifier = 'twitter'
    name = 'Twitter'
    url = 'https://twitter.com/jiten_mt'
    [menu.social.params]
      icon = 'brand-twitter'

  [[menu.social]]
    identifier = 'github'
    name = 'GitHub'
    url = 'https://github.com/jiten-thakkar'
    [menu.social.params]
      icon = 'brand-github'

# Taxonomies
[taxonomies]
  tag = 'tags'
  category = 'categories'

# Outputs
[outputs]
  home = ['HTML', 'RSS', 'JSON']

# Markup
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
